stages:
- name: Publish
  steps:
  - publishImageConfig:
      dockerfilePath: ./Dockerfile
      buildContext: .
      tag: openzaak:${CICD_EXECUTION_SEQUENCE}
- name: Deploy
  steps:
  - applyYamlConfig:
      path: ./deployment.yaml
    envFrom:
    - sourceName: open-zaak-secret
      sourceKey: ALLOWED_HOSTS
    - sourceName: open-zaak-secret
      sourceKey: CACHE_AXES
    - sourceName: open-zaak-secret
      sourceKey: CACHE_DEFAULT
    - sourceName: open-zaak-secret
      sourceKey: DJANGO_SETTINGS_MODULE
    - sourceName: open-zaak-secret
      sourceKey: IS_HTTPS
    - sourceName: open-zaak-secret
      sourceKey: SECRET_KEY
    - sourceName: open-zaak-secret
      sourceKey: SUBPATH
timeout: 45
branch:
  include:
  - tiltshift-rancher
notification: {}
